---
- name: Uninstall PostgreSQL
  hosts: 	petclinic-db
  become: yes
  vars:
    postgresql_packages:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - postgresql-client
    postgresql_data_directories:
      - /var/lib/pgsql
    postgresql_service_name: "postgresql" 

  tasks:
    - name: Stop PostgreSQL service
      ansible.builtin.service:
        name: "{{ postgresql_service_name }}"
        state: stopped
      ignore_errors: true

    - name: Disable PostgreSQL service
      ansible.builtin.service:
        name: "{{ postgresql_service_name }}"
        enabled: no
      ignore_errors: true

    - name: Remove PostgreSQL packages
      ansible.builtin.package:
        name: "{{ postgresql_packages }}"
        state: absent
      ignore_errors: true

    - name: Remove PostgreSQL data directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        recurse: yes
      loop: "{{ postgresql_data_directories }}"
      ignore_errors: true

    - name: Remove systemd service files (if any)
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ postgresql_service_name }}.service"
        state: absent
      ignore_errors: true

    - name: Reload systemd to apply changes
      ansible.builtin.systemd:
        daemon_reload: yes
      when: ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Debian'
      ignore_errors: true
