apiVersion: v1
data:
  application.properties: |
    quarkus.swagger-ui.always-include=true
    quarkus.http.cors=true
    quarkus.http.cors.origins=*
    quarkus.http.host=0.0.0.0
    quarkus.http.enable-compression=true
    quarkus.devservices.enabled=false

    auth-server-url=http://example-kc-service.keycloak:8080/realms/quarkus
    client-id=quarkus-app
    client-secret=lVGSvdaoDUem7lqeAnqXn1F92dCPbQea

    # Properties to have $WORKFLOW.identity populated
    quarkus.oidc.auth-server-url=${auth-server-url}
    quarkus.oidc.client-id=${client-id}
    quarkus.oidc.credentials.secret=${client-secret}
    quarkus.oidc.token.header=X-Authorization-Other
    quarkus.oidc.token.issuer=any

    # Properties for token propagation
    quarkus.oidc-client.BearerToken.auth-server-url=${auth-server-url}
    quarkus.oidc-client.BearerToken.token-path=${auth-server-url}/protocol/openid-connect/token
    quarkus.oidc-client.BearerToken.discovery-enabled=false
    quarkus.oidc-client.BearerToken.client-id=${client-id}
    quarkus.oidc-client.BearerToken.grant.type=client
    quarkus.oidc-client.BearerToken.credentials.client-secret.method=basic
    quarkus.oidc-client.BearerToken.credentials.client-secret.value=${client-secret}

    quarkus.openapi-generator.sample_server_yaml.auth.BearerToken.token-propagation=true
    quarkus.openapi-generator.sample_server_yaml.auth.BearerToken.header-name=X-Authorization-First

    quarkus.oidc-client.BearerTokenOther.auth-server-url=${auth-server-url}
    quarkus.oidc-client.BearerTokenOther.token-path=${auth-server-url}/protocol/openid-connect/token
    quarkus.oidc-client.BearerTokenOther.discovery-enabled=false
    quarkus.oidc-client.BearerTokenOther.client-id=${client-id}
    quarkus.oidc-client.BearerTokenOther.grant.type=client
    quarkus.oidc-client.BearerTokenOther.credentials.client-secret.method=basic
    quarkus.oidc-client.BearerTokenOther.credentials.client-secret.value=${client-secret}

    quarkus.openapi-generator.sample_server_yaml.auth.BearerTokenOther.token-propagation=true
    quarkus.openapi-generator.sample_server_yaml.auth.BearerTokenOther.header-name=X-Authorization-Other

    quarkus.openapi-generator.sample_server_yaml.auth.SimpleBearerToken.token-propagation=true
    quarkus.openapi-generator.sample_server_yaml.auth.SimpleBearerToken.header-name=X-Authorization-Simple

    quarkus.tls.trust-all=true
    quarkus.rest-client.sample_server_yaml.url=http://sample-server-service.rhdh-operator

    kie.flyway.enabled=true

    quarkus.log.category."org.apache.http".level=DEBUG
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: token-propagation
    app.kubernetes.io/component: serverless-workflow
    app.kubernetes.io/instance: token-propagation
    app.kubernetes.io/managed-by: sonataflow-operator
    app.kubernetes.io/name: token-propagation
    app.kubernetes.io/version: main
    sonataflow.org/workflow-app: token-propagation
    sonataflow.org/workflow-namespace: ""
  name: token-propagation-props
