apiVersion: v1
data:
  workflow-input-schema.json: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Workflow input parameters",
      "type": "object",
      "properties": {
        "orgName": {
          "title": "Organization Name",
          "type": "string",
          "description": "GitHub Organization Name"
        },
        "repoName": {
          "title": "Repository Name",
          "type": "string",
          "description": "GitHub Repository Name"
        },
        "serviceName": {
          "title": "Service Name",
          "type": "string",
          "description": "The Service Name"
        },
        "owner": {
          "title": "Owner",
          "type": "string",
          "description": "The owner of the component",
          "pattern": "^(user|group):[A-Za-z0-9]([-A-Za-z0-9]*[A-Za-z0-9])?/([A-Za-z0-9]([-A-Za-z0-9]*[A-Za-z0-9])?)$",
          "default": "user:default/guest"
        }
      },
      "required": [
        "orgName",
        "repoName",
        "serviceName",
        "owner"
      ]
    }
  workflow-output-schema.json: |-
    {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "WorkflowResult",
        "description": "Schema of workflow output",
        "type": "object",
        "properties": {
            "result": {
                "type": "object",
                "properties": {
                    "message": {
                        "description": "High-level summary of the current status, free-form text, human readable.",
                        "type": "string"
                    },
                    "nextWorkflows": {
                        "description": "List of workflows suggested to run next. Items at lower indexes are of higher priority.",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "description": "Workflow identifier",
                                    "type": "string"
                                },
                                "name": {
                                    "description": "Human readable title describing the workflow.",
                                    "type": "string"
                                }
                            },
                            "required": [
                                "id",
                                "name"
                            ]
                        }
                    },
                    "outputs": {
                        "description": "Additional structured output of workflow processing. This can contain identifiers of created resources, links to resources, logs or other output.",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "key": {
                                    "description": "Unique identifier of the option. Preferably human-readable.",
                                    "type": "string"
                                },
                                "value": {
                                    "description": "Free form value of the option.",
                                    "anyOf": [
                                        {
                                            "type": "string"
                                        },
                                        {
                                            "type": "number"
                                        }
                                    ]
                                },
                                "format": {
                                    "description": "More detailed type of the 'value' property. Defaults to 'text'.",
                                    "enum": [
                                        "text",
                                        "number",
                                        "link"
                                    ]
                                }
                            },
                            "required": [
                                "key",
                                "value"
                            ]
                        }
                    }
                }
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-software-template-workflow-resources-schemas
